source = ./modules/vars.conf
source = ./modules/windows.conf
source = ./modules/autostarts.conf
source = ./modules/keybinds.conf
source = ./modules/colors.conf
source = ./modules/decorations.conf

dwindle {
    preserve_split = true # You probably want this
}

misc {
		allow_session_lock_restore = true
}

permission = /usr/(bin|local/bin)/hyprpm, plugin, allow
