# Prefix
unbind C-b
set -g prefix C-s
bind C-s send-prefix

# Reload config
bind C-r source-file ~/.config/tmux/tmux.conf \; display "Config Reloaded!"

# Pane splits
unbind %
unbind '"'
bind e split-window -h -c "#{pane_current_path}"
bind o split-window -v -c "#{pane_current_path}"

# Windows
unbind t
bind t new-window -c "#{pane_current_path}"
bind T clock-mode

# Search
unbind f
bind f copy-mode \; command-prompt -p "Search:" "send-keys -X search-forward '%%'"

# Copy mode
set -g mode-keys vi
unbind -T copy-mode-vi MouseDragEnd1Pane

# Resurrect plugin
set -g @resurrect-save 'S'
set -g @resurrect-restore 'R'


# Popups
bind C-l if-shell \
	'git -C "#{pane_current_path}" rev-parse --is-inside-work-tree >/dev/null 2>&1' \
	'display-popup -d "#{pane_current_path}" -w 90% -h 90% -E "lazygit"' \
	'display-message "Git repo not found"'

bind C-p display-menu -T "#[align=centre]Dev Menu" \
    -x C -y C \
    "" \
    "Edit Dotfiles"        d "new-window -c ~ 'cd dotfiles && nvim .'" \
    "Edit .zshrc"          z "display-popup -E 'nvim ~/.zshrc'" \
