# Status appearance
set -g window-style 'bg=default'
set -g window-active-style 'bg=default'
set -g status-bg default
set -g status-style bg=default

# Window format
set -g window-status-format "#[fg=#{E:@thm_text_variant}]#[fg=#{E:@thm_surface},bg=#{E:@thm_text_variant}]#I #[fg=#{E:@thm_primary},bg=#{E:@thm_surface}] #W#[fg=#{E:@thm_surface},bg=default]"

set -g window-status-current-format "#[fg=#{E:@thm_primary}]#[fg=#{E:@thm_surface},bg=#{E:@thm_primary}]#I #[fg=#{E:@thm_primary},bg=#{E:@thm_surface}] 󰐾#[fg=#{E:@thm_surface},bg=default]"

# Length
set -g status-left-length 40
set -g status-right-length 40

# Left modules
set -g status-left ""
set -ag status-left "#{?client_prefix,#[bg=default]#[fg=@thm_fg] ⌨ ,}"
set -ag status-left "#{?#{==:#{pane_mode},copy-mode},#[bg=default]#[fg=@thm_fg] 󰆿 ,}"

# Right modules
set -g status-right "#(~/.wraith/scripts/tmux-git-status.sh '#{pane_current_path}') "
set -ag status-right "#[fg=#{E:@thm_primary}]#[fg=#{E:@thm_surface},bg=#{E:@thm_primary}] #[fg=#{E:@thm_primary},bg=#{E:@thm_surface}] %I:%M %p#[fg=#{E:@thm_surface},bg=default]"
