$image = /home/robin/.assets/wallpapers/ferrari.jpg

$background = rgba(19120aff)

$error = rgba(ffb4abff)

$error_container = rgba(93000aff)

$inverse_on_surface = rgba(382f25ff)

$inverse_primary = rgba(865300ff)

$inverse_surface = rgba(f0e0d1ff)

$on_background = rgba(f0e0d1ff)

$on_error = rgba(690005ff)

$on_error_container = rgba(ffdad6ff)

$on_primary = rgba(472a00ff)

$on_primary_container = rgba(351e00ff)

$on_primary_fixed = rgba(2b1700ff)

$on_primary_fixed_variant = rgba(663e00ff)

$on_secondary = rgba(472a00ff)

$on_secondary_container = rgba(ffdab3ff)

$on_secondary_fixed = rgba(2b1700ff)

$on_secondary_fixed_variant = rgba(633f0fff)

$on_surface = rgba(f0e0d1ff)

$on_surface_variant = rgba(d9c3adff)

$on_tertiary = rgba(00344bff)

$on_tertiary_container = rgba(002638ff)

$on_tertiary_fixed = rgba(001e2dff)

$on_tertiary_fixed_variant = rgba(004c6bff)

$outline = rgba(a18d7aff)

$outline_variant = rgba(534434ff)

$primary = rgba(ffbd6eff)

$primary_container = rgba(f49a02ff)

$primary_fixed = rgba(ffddb9ff)

$primary_fixed_dim = rgba(ffb963ff)

$scrim = rgba(000000ff)

$secondary = rgba(f1bd82ff)

$secondary_container = rgba(633f0fff)

$secondary_fixed = rgba(ffddb9ff)

$secondary_fixed_dim = rgba(f1bd82ff)

$shadow = rgba(000000ff)

$source_color = rgba(f49a02ff)

$surface = rgba(19120aff)

$surface_bright = rgba(41372eff)

$surface_container = rgba(261e15ff)

$surface_container_high = rgba(31281fff)

$surface_container_highest = rgba(3d3329ff)

$surface_container_low = rgba(221a11ff)

$surface_container_lowest = rgba(140d06ff)

$surface_dim = rgba(19120aff)

$surface_tint = rgba(ffb963ff)

$surface_variant = rgba(534434ff)

$tertiary = rgba(8ad2ffff)

$tertiary_container = rgba(00baffff)

$tertiary_fixed = rgba(c6e7ffff)

$tertiary_fixed_dim = rgba(81cfffff)

