exec-once = waybar &
exec-once = swaync &
exec-once = hyprctl dispatch workspace "Code"
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store 
exec-once = hyprctl setcursor "ArcStarry" 25
exec-once = hypridle &
exec-once = awww-daemon 
exec-once = hyprpm reload
